%% This file were automatically generated by SWIG's MatLab module
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                         %%
%%                INTEL CORPORATION PROPRIETARY INFORMATION                %%
%%   This software is supplied under the terms of a license agreement or   %%
%%  nondisclosure agreement with Intel Corporation and may not be copied   %%
%%   or disclosed except in accordance with the terms of that agreement.   %%
%%       Copyright (c) 2003 Intel Corporation. All Rights Reserved.        %%
%%                                                                         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% [] = AttachMatrix(varargin)
%%
%% C++ prototype: void AttachMatrix(pnl::CFactor *self,pnl::CMatrix<float > *matrix,pnl::EMatrixType mType,int numberOfMatrix,int const *discrParentValuesIndices)
%%

function [] = AttachMatrix(varargin)

feval('pnl_full', 'CFactor_AttachMatrix_wrap', varargin{:});

return
