%% This file were automatically generated by SWIG's MatLab module
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                         %%
%%                INTEL CORPORATION PROPRIETARY INFORMATION                %%
%%   This software is supplied under the terms of a license agreement or   %%
%%  nondisclosure agreement with Intel Corporation and may not be copied   %%
%%   or disclosed except in accordance with the terms of that agreement.   %%
%%       Copyright (c) 2003 Intel Corporation. All Rights Reserved.        %%
%%                                                                         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% [result] = GetMatrix(varargin)
%%
%% C++ prototype: pnl::CMatrix<float > *GetMatrix(pnl::CFactor const *self,pnl::EMatrixType mType,int numberOfMatrix,int const *discrParentValuesIndices)
%%

function [result] = GetMatrix(varargin)

[result] = feval('pnl_full', 'CFactor_GetMatrix_wrap', varargin{:});

return
