%% This file were automatically generated by SWIG's MatLab module
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                         %%
%%                INTEL CORPORATION PROPRIETARY INFORMATION                %%
%%   This software is supplied under the terms of a license agreement or   %%
%%  nondisclosure agreement with Intel Corporation and may not be copied   %%
%%   or disclosed except in accordance with the terms of that agreement.   %%
%%       Copyright (c) 2003 Intel Corporation. All Rights Reserved.        %%
%%                                                                         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% [result] = GetMPE(varargin)
%%
%% C++ prototype: pnl::CEvidence const *GetMPE(pnl::C1_5SliceJtreeInfEngine *self)
%%

function [result] = GetMPE(varargin)

[result] = feval('pnl_full', 'C1_5SliceJtreeInfEngine_GetMPE_wrap', varargin{:});
result = CEvidence('%%@#DefaultCtor', result);

return
