
AM_CPPFLAGS=-x c++ $(DEBUG)
PNLD=$(top_srcdir)/c_pgmtk
PNL_LIBS=$(PNLD)/src/libpnl.la $(top_srcdir)/cxcore/cxcore/src/libcxcore.a
PNL_INCL=-I$(top_srcdir)/cxcore/cxcore/include -I$(PNLD)/include -I$(PNLD)/src/include/cart -I$(PNLD)/src/include

