%% This file were automatically generated by SWIG's MatLab module
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                         %%
%%                INTEL CORPORATION PROPRIETARY INFORMATION                %%
%%   This software is supplied under the terms of a license agreement or   %%
%%  nondisclosure agreement with Intel Corporation and may not be copied   %%
%%   or disclosed except in accordance with the terms of that agreement.   %%
%%       Copyright (c) 2003 Intel Corporation. All Rights Reserved.        %%
%%                                                                         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% [] = EnterEvidence(varargin)
%%
%% C++ prototype: void EnterEvidence(pnl::CSamplingInfEngine *self,pnl::CEvidence const *pEvidenceIn,int maximize,int sumOnMixtureNode)
%%

function [] = EnterEvidence(varargin)

feval('pnl_full', 'CSamplingInfEngine_EnterEvidence_wrap', varargin{:});

return
