%% This file were automatically generated by SWIG's MatLab module
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                         %%
%%                INTEL CORPORATION PROPRIETARY INFORMATION                %%
%%   This software is supplied under the terms of a license agreement or   %%
%%  nondisclosure agreement with Intel Corporation and may not be copied   %%
%%   or disclosed except in accordance with the terms of that agreement.   %%
%%       Copyright (c) 2003 Intel Corporation. All Rights Reserved.        %%
%%                                                                         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% [OUTPUTOut1] = GenerateSamples(varargin)
%%
%% C++ prototype: void GenerateSamples(pnl::CMNet const *self,pnl::pEvidencesVector *OUTPUT,int nSamples,pnl::CEvidence const *pEvIn)
%%

function [OUTPUTOut1] = GenerateSamples(varargin)

[OUTPUTOut1] = feval('pnl_full', 'CMNet_GenerateSamples_wrap', varargin{:});
for k = 1:length(OUTPUTOut1)
    OUTPUTOut1{k} = CEvidence('%%@#DefaultCtor', OUTPUTOut1{k});
end

return
