%% This file were automatically generated by SWIG's MatLab module
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                         %%
%%                INTEL CORPORATION PROPRIETARY INFORMATION                %%
%%   This software is supplied under the terms of a license agreement or   %%
%%  nondisclosure agreement with Intel Corporation and may not be copied   %%
%%   or disclosed except in accordance with the terms of that agreement.   %%
%%       Copyright (c) 2003 Intel Corporation. All Rights Reserved.        %%
%%                                                                         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% [OUTPUTOut1, OUTPUTOut2, OUTPUTOut3] = GetMultipliedDelta(varargin)
%%
%% C++ prototype: void GetMultipliedDelta(pnl::CPotential const *self,pnl::intVector *OUTPUT,pnl::floatVector *OUTPUT,pnl::intVector *OUTPUT)
%%

function [OUTPUTOut1, OUTPUTOut2, OUTPUTOut3] = GetMultipliedDelta(varargin)

[OUTPUTOut1, OUTPUTOut2, OUTPUTOut3] = feval('pnl_full', 'CPotential_GetMultipliedDelta_wrap', varargin{:});

return
