%% This file were automatically generated by SWIG's MatLab module
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                         %%
%%                INTEL CORPORATION PROPRIETARY INFORMATION                %%
%%   This software is supplied under the terms of a license agreement or   %%
%%  nondisclosure agreement with Intel Corporation and may not be copied   %%
%%   or disclosed except in accordance with the terms of that agreement.   %%
%%       Copyright (c) 2003 Intel Corporation. All Rights Reserved.        %%
%%                                                                         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% [] = UpdateStatisticsEM(varargin)
%%
%% C++ prototype: void UpdateStatisticsEM(pnl::CPotential *self,pnl::CPotential const *pMargPot,pnl::CEvidence const *pEvidence)
%%

function [] = UpdateStatisticsEM(varargin)

feval('pnl_full', 'CPotential_UpdateStatisticsEM_wrap', varargin{:});

return
