%% This file were automatically generated by SWIG's MatLab module
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                         %%
%%                INTEL CORPORATION PROPRIETARY INFORMATION                %%
%%   This software is supplied under the terms of a license agreement or   %%
%%  nondisclosure agreement with Intel Corporation and may not be copied   %%
%%   or disclosed except in accordance with the terms of that agreement.   %%
%%       Copyright (c) 2003 Intel Corporation. All Rights Reserved.        %%
%%                                                                         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% [] = MarginalNodes(varargin)
%%
%% C++ prototype: void MarginalNodes(pnl::CGibbsWithAnnealingInfEngine *self,pnl::intVector const &queryNdsIn,int notExpandJPD)
%%

function [] = MarginalNodes(varargin)

feval('pnl_full', 'CGibbsWithAnnealingInfEngine_MarginalNodes_wrap', varargin{:});

return
