%% This file were automatically generated by SWIG's MatLab module
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                         %%
%%                INTEL CORPORATION PROPRIETARY INFORMATION                %%
%%   This software is supplied under the terms of a license agreement or   %%
%%  nondisclosure agreement with Intel Corporation and may not be copied   %%
%%   or disclosed except in accordance with the terms of that agreement.   %%
%%       Copyright (c) 2003 Intel Corporation. All Rights Reserved.        %%
%%                                                                         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% [result] = CGaussianPotential(varargin)
%%
%% CGaussianPotential: Help not provided
%%


function [result] = CGaussianPotential(varargin)

if nargin == 2 & ischar(varargin{1}) & strcmp(varargin{1}, '%%@#DefaultCtor')
    if ~ischar(varargin{2})
        error ('internal error during call to default ctor: arg2 ~ischar');
    end
    result.ptrString = varargin{2};
    base = CPotential('%%@#DefaultCtor', result.ptrString);
    result = class(result, 'CGaussianPotential', base);
    return
end

if nargin > 1 & nargin < 8
    result.ptrString = feval('pnl_full', 'CGaussianPotential_Create_wrap', varargin{:});
    base = CPotential('%%@#DefaultCtor', result.ptrString);
    result = class(result, 'CGaussianPotential', base);
    return
end

if nargin > 0 & nargin < 2
    result.ptrString = feval('pnl_full', 'CGaussianPotential_Copy_wrap', varargin{:});
    base = CPotential('%%@#DefaultCtor', result.ptrString);
    result = class(result, 'CGaussianPotential', base);
    return
end

if nargin > 2 & nargin < 6
    result.ptrString = feval('pnl_full', 'CGaussianPotential_CreateDeltaF_wrap', varargin{:});
    base = CPotential('%%@#DefaultCtor', result.ptrString);
    result = class(result, 'CGaussianPotential', base);
    return
end

if nargin > 1 & nargin < 5
    result.ptrString = feval('pnl_full', 'CGaussianPotential_CreateUnitF_wrap', varargin{:});
    base = CPotential('%%@#DefaultCtor', result.ptrString);
    result = class(result, 'CGaussianPotential', base);
    return
end

error('Wrong number of input arguments')
