%% This file were automatically generated by SWIG's MatLab module
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                         %%
%%                INTEL CORPORATION PROPRIETARY INFORMATION                %%
%%   This software is supplied under the terms of a license agreement or   %%
%%  nondisclosure agreement with Intel Corporation and may not be copied   %%
%%   or disclosed except in accordance with the terms of that agreement.   %%
%%       Copyright (c) 2003 Intel Corporation. All Rights Reserved.        %%
%%                                                                         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% [result] = Combine(varargin)
%%
%% C++ prototype: pnl::CIDPotential *Combine(pnl::CIDPotential const *self,pnl::CIDPotential const *pOtherFactor,pnl::CIDPotential *output)
%%

function [result] = Combine(varargin)

[result] = feval('pnl_full', 'CIDPotential_Combine_wrap', varargin{:});
result = CIDPotential('%%@#DefaultCtor', result);

return
