%% This file were automatically generated by SWIG's MatLab module
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                         %%
%%                INTEL CORPORATION PROPRIETARY INFORMATION                %%
%%   This software is supplied under the terms of a license agreement or   %%
%%  nondisclosure agreement with Intel Corporation and may not be copied   %%
%%   or disclosed except in accordance with the terms of that agreement.   %%
%%       Copyright (c) 2003 Intel Corporation. All Rights Reserved.        %%
%%                                                                         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% [OUTPUTOut1] = GenerateSamples(varargin)
%%
%% C++ prototype: void GenerateSamples(pnl::CDBN const *self,pnl::pEvidencesVecVector *OUTPUT,pnl::intVector const &nSlices)
%%

function [OUTPUTOut1] = GenerateSamples(varargin)

[OUTPUTOut1] = feval('pnl_full', 'CDBN_GenerateSamples_wrap', varargin{:});
for i = 1:length(OUTPUTOut1)
    tmp = OUTPUTOut1{i};
    for j = 1:length(tmp)
        tmp{j} = CEvidence('%%@#DefaultCtor', tmp{j});
        end
    OUTPUTOut1{i} = tmp;
    end
clear tmp;
return
