%% This file were automatically generated by SWIG's MatLab module
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                         %%
%%                INTEL CORPORATION PROPRIETARY INFORMATION                %%
%%   This software is supplied under the terms of a license agreement or   %%
%%  nondisclosure agreement with Intel Corporation and may not be copied   %%
%%   or disclosed except in accordance with the terms of that agreement.   %%
%%       Copyright (c) 2003 Intel Corporation. All Rights Reserved.        %%
%%                                                                         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% [] = InitCharge(varargin)
%%
%% C++ prototype: void InitCharge(pnl::CJunctionTree *self,pnl::CStaticGraphicalModel const *pGrModel,pnl::CEvidence const *pEvidence,int sumOnMixtureNode)
%%

function [] = InitCharge(varargin)

feval('pnl_full', 'CJunctionTree_InitCharge_wrap', varargin{:});

return
