%% This file were automatically generated by SWIG's MatLab module
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                         %%
%%                INTEL CORPORATION PROPRIETARY INFORMATION                %%
%%   This software is supplied under the terms of a license agreement or   %%
%%  nondisclosure agreement with Intel Corporation and may not be copied   %%
%%   or disclosed except in accordance with the terms of that agreement.   %%
%%       Copyright (c) 2003 Intel Corporation. All Rights Reserved.        %%
%%                                                                         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% [OUTPUTOut1] = GetConnectivityComponents(varargin)
%%
%% C++ prototype: void GetConnectivityComponents(pnl::CGraph const *self,pnl::intVecVector *OUTPUT)
%%

function [OUTPUTOut1] = GetConnectivityComponents(varargin)

[OUTPUTOut1] = feval('pnl_full', 'CGraph_GetConnectivityComponents_wrap', varargin{:});

return
