%% This file were automatically generated by SWIG's MatLab module
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                         %%
%%                INTEL CORPORATION PROPRIETARY INFORMATION                %%
%%   This software is supplied under the terms of a license agreement or   %%
%%  nondisclosure agreement with Intel Corporation and may not be copied   %%
%%   or disclosed except in accordance with the terms of that agreement.   %%
%%       Copyright (c) 2003 Intel Corporation. All Rights Reserved.        %%
%%                                                                         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% [OUTPUTOut1, OUTPUTOut2] = GetNeighbors(varargin)
%%
%% C++ prototype: void GetNeighbors(pnl::CGraph const *self,int nodeNum,pnl::intVector *OUTPUT,pnl::neighborTypeVector *OUTPUT)
%%

function [OUTPUTOut1, OUTPUTOut2] = GetNeighbors(varargin)

[OUTPUTOut1, OUTPUTOut2] = feval('pnl_full', 'CGraph_GetNeighbors_wrap', varargin{:});

return
