%% This file were automatically generated by SWIG's MatLab module
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                         %%
%%                INTEL CORPORATION PROPRIETARY INFORMATION                %%
%%   This software is supplied under the terms of a license agreement or   %%
%%  nondisclosure agreement with Intel Corporation and may not be copied   %%
%%   or disclosed except in accordance with the terms of that agreement.   %%
%%       Copyright (c) 2003 Intel Corporation. All Rights Reserved.        %%
%%                                                                         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% [] = ShrinkObsNdsForAllFactors(varargin)
%%
%% C++ prototype: void ShrinkObsNdsForAllFactors(pnl::CFactors *self,pnl::CEvidence const *pEvidenceIn)
%%

function [] = ShrinkObsNdsForAllFactors(varargin)

feval('pnl_full', 'CFactors_ShrinkObsNdsForAllFactors_wrap', varargin{:});

return
