%% This file were automatically generated by SWIG's MatLab module
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                         %%
%%                INTEL CORPORATION PROPRIETARY INFORMATION                %%
%%   This software is supplied under the terms of a license agreement or   %%
%%  nondisclosure agreement with Intel Corporation and may not be copied   %%
%%   or disclosed except in accordance with the terms of that agreement.   %%
%%       Copyright (c) 2003 Intel Corporation. All Rights Reserved.        %%
%%                                                                         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% [] = AllocDistribution(varargin)
%%
%% C++ prototype: void AllocDistribution(pnl::CSoftMaxCPD *self,pnl::floatVector const &weightsIn,pnl::floatVector const &offsetIn,pnl::intVector const &parentCombination)
%%

function [] = AllocDistribution(varargin)

feval('pnl_full', 'CSoftMaxCPD_AllocDistribution_wrap', varargin{:});

return
