%% This file were automatically generated by SWIG's MatLab module
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                         %%
%%                INTEL CORPORATION PROPRIETARY INFORMATION                %%
%%   This software is supplied under the terms of a license agreement or   %%
%%  nondisclosure agreement with Intel Corporation and may not be copied   %%
%%   or disclosed except in accordance with the terms of that agreement.   %%
%%       Copyright (c) 2003 Intel Corporation. All Rights Reserved.        %%
%%                                                                         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% [result, OUTPUTOut2] = IsValidAsBaseForDynamicModel(varargin)
%%
%% C++ prototype: bool IsValidAsBaseForDynamicModel(pnl::CStaticGraphicalModel const *self,std::string *OUTPUT)
%%

function [result, OUTPUTOut2] = IsValidAsBaseForDynamicModel(varargin)

[result, OUTPUTOut2] = feval('pnl_full', 'CStaticGraphicalModel_IsValidAsBaseForDynamicModel_wrap', varargin{:});

return
