%% This file were automatically generated by SWIG's MatLab module
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                         %%
%%                INTEL CORPORATION PROPRIETARY INFORMATION                %%
%%   This software is supplied under the terms of a license agreement or   %%
%%  nondisclosure agreement with Intel Corporation and may not be copied   %%
%%   or disclosed except in accordance with the terms of that agreement.   %%
%%       Copyright (c) 2003 Intel Corporation. All Rights Reserved.        %%
%%                                                                         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% [] = ShrinkObserved(varargin)
%%
%% C++ prototype: void ShrinkObserved(pnl::CJtreeInfEngine *self,pnl::CEvidence const *pEvidenceIn,int maximize,int sumOnMixtureNode,bool bRebuildJTree)
%%

function [] = ShrinkObserved(varargin)

feval('pnl_full', 'CJtreeInfEngine_ShrinkObserved_wrap', varargin{:});

return
