%% This file were automatically generated by SWIG's MatLab module
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                         %%
%%                INTEL CORPORATION PROPRIETARY INFORMATION                %%
%%   This software is supplied under the terms of a license agreement or   %%
%%  nondisclosure agreement with Intel Corporation and may not be copied   %%
%%   or disclosed except in accordance with the terms of that agreement.   %%
%%       Copyright (c) 2003 Intel Corporation. All Rights Reserved.        %%
%%                                                                         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% [result] = CreateByNodeValues(varargin)
%%
%% C++ prototype: pnl::CEvidence *pnl::CEvidence::Create(pnl::CNodeValues const *values,pnl::intVector const &obsNodesIn,pnl::CModelDomain const *pMD,int takeIntoObservationFlags)
%%

function [result] = CreateByNodeValues(varargin)

[result] = feval('pnl_full', 'CEvidence_CreateByNodeValues_wrap', varargin{:});
result = CEvidence('%%@#DefaultCtor', result);

return
