%% This file were automatically generated by SWIG's MatLab module
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                         %%
%%                INTEL CORPORATION PROPRIETARY INFORMATION                %%
%%   This software is supplied under the terms of a license agreement or   %%
%%  nondisclosure agreement with Intel Corporation and may not be copied   %%
%%   or disclosed except in accordance with the terms of that agreement.   %%
%%       Copyright (c) 2003 Intel Corporation. All Rights Reserved.        %%
%%                                                                         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% [result] = CopyWithNewDomain(varargin)
%%
%% C++ prototype: pnl::CFactor *pnl::CFactor::CopyWithNewDomain(pnl::CFactor const *factor,pnl::intVector &domain,pnl::CModelDomain *pModelDomain,pnl::intVector const &obsIndices)
%%

function [result] = CopyWithNewDomain(varargin)

[result] = feval('pnl_full', 'CFactor_CopyWithNewDomain_wrap', varargin{:});
result = CFactor('%%@#DefaultCtor', result);

return
