%% This file were automatically generated by SWIG's MatLab module
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                         %%
%%                INTEL CORPORATION PROPRIETARY INFORMATION                %%
%%   This software is supplied under the terms of a license agreement or   %%
%%  nondisclosure agreement with Intel Corporation and may not be copied   %%
%%   or disclosed except in accordance with the terms of that agreement.   %%
%%       Copyright (c) 2003 Intel Corporation. All Rights Reserved.        %%
%%                                                                         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% [result] = Create(varargin)
%%
%% C++ prototype: pnl::CGaussianPotential *pnl::CGaussianPotential::Create(pnl::CModelDomain *pMD,pnl::intVector const &domainIn,int inMoment,pnl::C2DNumericDenseMatrix<float > const *meanIn,pnl::C2DNumericDenseMatrix<float > const *covIn,float normCoeff,pnl::intVector const &obsIndicesIn)
%%

function [result] = Create(varargin)

[result] = feval('pnl_full', 'CGaussianPotential_Create_wrap', varargin{:});
result = CGaussianPotential('%%@#DefaultCtor', result);

return
