%% This file were automatically generated by SWIG's MatLab module
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                         %%
%%                INTEL CORPORATION PROPRIETARY INFORMATION                %%
%%   This software is supplied under the terms of a license agreement or   %%
%%  nondisclosure agreement with Intel Corporation and may not be copied   %%
%%   or disclosed except in accordance with the terms of that agreement.   %%
%%       Copyright (c) 2003 Intel Corporation. All Rights Reserved.        %%
%%                                                                         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% [result] = CreateFromJTree(varargin)
%%
%% C++ prototype: pnl::CJtreeInfEngine *pnl::CJtreeInfEngine::Create(pnl::CStaticGraphicalModel const *pGraphicalModelIn,pnl::CJunctionTree *pJTreeIn)
%%

function [result] = CreateFromJTree(varargin)

[result] = feval('pnl_full', 'CJtreeInfEngine_CreateFromJTree_wrap', varargin{:});
result = CJtreeInfEngine('%%@#DefaultCtor', result);

return
