%% This file were automatically generated by SWIG's MatLab module
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                         %%
%%                INTEL CORPORATION PROPRIETARY INFORMATION                %%
%%   This software is supplied under the terms of a license agreement or   %%
%%  nondisclosure agreement with Intel Corporation and may not be copied   %%
%%   or disclosed except in accordance with the terms of that agreement.   %%
%%       Copyright (c) 2003 Intel Corporation. All Rights Reserved.        %%
%%                                                                         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% [result] = CreateIfAllTheSame(varargin)
%%
%% C++ prototype: pnl::CModelDomain *pnl::CModelDomain::Create(int numVariables,pnl::CNodeType const &commonVariableType,pnl::CGraphicalModel *pCreaterOfMD)
%%

function [result] = CreateIfAllTheSame(varargin)

[result] = feval('pnl_full', 'CModelDomain_CreateIfAllTheSame_wrap', varargin{:});
result = CModelDomain('%%@#DefaultCtor', result);

return
