%% This file were automatically generated by SWIG's MatLab module
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                         %%
%%                INTEL CORPORATION PROPRIETARY INFORMATION                %%
%%   This software is supplied under the terms of a license agreement or   %%
%%  nondisclosure agreement with Intel Corporation and may not be copied   %%
%%   or disclosed except in accordance with the terms of that agreement.   %%
%%       Copyright (c) 2003 Intel Corporation. All Rights Reserved.        %%
%%                                                                         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% [result] = pnlExCreateRandomDBN(varargin)
%%
%% C++ prototype: pnl::CDBN *pnl::pnlExCreateRandomDBN(int nnodesPerSlice,int nEdges,int nInterfNds,int nContNdsPerSlice,int maxSzDiscrNds,int maxSzContNds)
%%

function [result] = pnlExCreateRandomDBN(varargin)

[result] = feval('pnl_full', 'pnlExCreateRandomDBN_wrap', varargin{:});
result = CDBN('%%@#DefaultCtor', result);

return
