%% This file were automatically generated by SWIG's MatLab module
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                         %%
%%                INTEL CORPORATION PROPRIETARY INFORMATION                %%
%%   This software is supplied under the terms of a license agreement or   %%
%%  nondisclosure agreement with Intel Corporation and may not be copied   %%
%%   or disclosed except in accordance with the terms of that agreement.   %%
%%       Copyright (c) 2003 Intel Corporation. All Rights Reserved.        %%
%%                                                                         %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% [result] = pnlExCreateBigMRF2(varargin)
%%
%% C++ prototype: pnl::CMRF2 *pnl::pnlExCreateBigMRF2(int variant,int m_numOfRows,int m_numOfCols,int m_Kolkand,float sigmahor,float sigmaver)
%%

function [result] = pnlExCreateBigMRF2(varargin)

[result] = feval('pnl_full', 'pnlExCreateBigMRF2_wrap', varargin{:});
result = CMRF2('%%@#DefaultCtor', result);

return
